"""empty message

Revision ID: 417cabb878c8
Revises: cde3f7c96297
Create Date: 2021-01-12 22:41:34.114125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417cabb878c8'
down_revision = 'cde3f7c96297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('postslug', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'postslug')
    # ### end Alembic commands ###
