"""empty message

Revision ID: cde3f7c96297
Revises: 
Create Date: 2021-01-12 22:21:27.243467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cde3f7c96297'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
